loginproj/authentication/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('',views.signin,name = 'signin'),
    path('signup',views.signup,name = 'signup'),
    path('home',views.home,name = 'home'),
    path('signout',views.signout,name = 'signout'),
    path('profile',views.profile,name = 'profile'),
]

loginproj/customadmin/urls.py
from django.urls import include, path
from . import views
app_name='customadmin'
urlpatterns = [
    path('adminsignin',views.adminsignin,name = 'adminsignin'),
    path('adminhome', views.adminhome, name='adminhome'),
    path('adminsignout',views.adminsignout,name = 'adminsignout'),
    path('manageusers',views.manageusers,name = 'manageusers'),
    path('deleteuser/<int:userid>',views.deleteuser,name = 'deleteuser'),
    path('edituser/<int:userid>',views.edituser,name = 'edituser'),
    path('createuser',views.createuser,name = 'createuser'),
]

loginproj/loginproj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authentication.urls')),
    path('customadmin/', include('customadmin.urls'))
]

loginproj/authentication/models.py
from django.db import models

class User(models.Model):
    firstname = models.CharField(max_length=200)
    lastname = models.CharField(max_length=200)
    email = models.CharField(unique=True)
    username = models.CharField(max_length=200, unique=True)
    password = models.CharField()

loginproj/authentication/forms.py
from django import forms
from .models import User
from django.forms import ModelForm

class Signinform(forms.Form):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget = forms.PasswordInput(attrs={'placeholder': 'Password'}))

    username.label = ''
    password.label = ''

class Signupform(forms.ModelForm):
    confirm_password = forms.CharField(widget = forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))
    confirm_password.label = ''

    class Meta:
        model = User
        fields = "__all__"
        labels = {
            'firstname' : '',
            'lastname' : '',
            'email' : '',
            'username' : '',
            'password' : '',
        }
        widgets = {
            'firstname' : forms.TextInput(attrs={'placeholder':'First Name'}),
            'lastname' : forms.TextInput(attrs={'placeholder':'Last Name'}),
            'email' : forms.TextInput(attrs={'placeholder':'Email'}),
            'username' : forms.TextInput(attrs={'placeholder':'Username'}),
            'password': forms.PasswordInput(attrs={'placeholder':'Password'}),
            'confirm_password' : forms.PasswordInput(attrs={'placeholder':'Confirm Password'}),
        }

loginproj/authentication/views.py
from django.shortcuts import redirect, render
from .forms import Signinform,Signupform
from django.contrib import messages,auth
from .models import User
from django.views.decorators.cache import never_cache

# Create your views here.
@never_cache
def signin(request):
    if 'username' in request.session:
        return redirect('home')
    if 'uname' in request.session:
        return redirect('customadmin:adminhome')
    if request.method == 'POST':
        form = Signinform(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user_exists = User.objects.filter(username=username, password=password).exists()
            
            if user_exists:
                user = User.objects.get(username=username)
                request.session['uid'] = user.id
                request.session['firstname'] = user.firstname
                request.session['lastname'] = user.lastname
                request.session['username'] = user.username
                request.session['email'] = user.email
                return redirect('home')
                
            else:
                messages.error(request,'Invalid username or password.')
        
    else:
        form = Signinform()

    return render(request, 'authentication/signin.html', {'form':form})

@never_cache
def signup(request):
    if 'username' in request.session:
        return redirect('home')
    else:
        if request.method == "POST":
            form = Signupform(request.POST)
            if form.is_valid():
                password = form.cleaned_data['password']
                confirm_password = form.cleaned_data['confirm_password']

                if confirm_password!=password:
                    messages.success(request, "Password's doesn't match")
                    return redirect('signup')
                else:
                    form.save()
                    messages.success(request, 'Account created successfully')
                    return redirect('signin')
        else:
            form = Signupform()

    return render(request,'authentication/signup.html',{'form': form})

@never_cache
def home(request):
    if 'uid' in request.session: 
        firstname = request.session.get("firstname")
        return render(request, 'authentication/home.html', {'firstname': firstname})
    else:
        return redirect('signin')

def signout(request):
    if 'uid' in request.session:
        request.session.flush()
    messages.success(request,'You have logged out successfully')
    return redirect('signin')

@never_cache
def profile(request):
    if 'uid' not in request.session:
        return redirect('signin')
    user_id = request.session.get("uid")
    try:
        user = User.objects.get(id = user_id)
    except:
        return redirect('signin')
    
    
    return render(request, 'authentication/profile.html', {'user':user})

loginproj/authentication/templates/authentication/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body style="margin: 0; padding: 0; height: 100%;">

    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }

        .background-radial-gradient {
            background-color: hsl(218, 41%, 15%);
            background-image: radial-gradient(650px circle at 0% 0%, hsl(218, 41%, 35%) 15%, hsl(218, 41%, 30%) 35%, hsl(218, 41%, 20%) 75%, hsl(218, 41%, 19%) 80%, transparent 100%), radial-gradient(1250px circle at 100% 100%, hsl(218, 41%, 45%) 15%, hsl(218, 41%, 30%) 35%, hsl(218, 41%, 20%) 75%, hsl(218, 41%, 19%) 80%, transparent 100%);
            background-size: 100% 100%;
            height: 100%;
        }
        .btn-danger a{
            color: white;
            text-decoration: none;
        }
        .btn-primary a{
            color: white;
            text-decoration: none;
        }
    </style>
    
    <!-- Section: Design Block -->
    <section class="background-radial-gradient overflow-hidden">
        <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
            <div class="row gx-lg-5 align-items-center mb-5">

                    {% for message in messages %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>Success:</strong> {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% elif message.tags == 'error' %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>Error:</strong> {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <h1 class="my-5 display-5 fw-bold ls-tight text-center" style="color: hsl(218, 81%, 95%)">
                        Hey, {{ firstname }} You have<br />
                        <span style="color: hsl(218, 81%, 75%)">Logged in Successfully</span>
                    </h1>
            <div class="d-flex flex-column align-items-center">
                <a href="{% url 'profile' %}"><button type="submit" class="btn btn-primary btn-block mb-4">
                    View Profile
                </button></a>
                <a href="{% url 'signout' %}"><button type="submit" class="btn btn-danger btn-block mb-4">
                    Logout
                </button></a>
            </div>
            </div>
        </div>
    </section>
    <!-- Section: Design Block -->

</body>
</html>

loginproj/authentication/templates/authentication/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body style="margin: 0; padding: 0; height: 100%;">

    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }

        .background-radial-gradient {
            background-color: hsl(218, 41%, 15%);
            background-image: radial-gradient(650px circle at 0% 0%, hsl(218, 41%, 35%) 15%, hsl(218, 41%, 30%) 35%, hsl(218, 41%, 20%) 75%, hsl(218, 41%, 19%) 80%, transparent 100%), radial-gradient(1250px circle at 100% 100%, hsl(218, 41%, 45%) 15%, hsl(218, 41%, 30%) 35%, hsl(218, 41%, 20%) 75%, hsl(218, 41%, 19%) 80%, transparent 100%);
            background-size: 100% 100%;
            height: 100%;
        }

        .table-container {
            width: 80%;
            margin: auto;
        }

        .profile-table {
            width: 100%;
            margin-top: 20px;
          
        }

        .profile-table th, .profile-table td {
            padding: 10px;
            text-align: left;
            background-color: white;
            color: hsl(218, 81%, 25%); /* Darker text for better contrast */
        }

        .btn-back-to-home {
            margin-top: 30px; /* Adjust the margin-top value as needed */
        }
    </style>

    <section class="background-radial-gradient overflow-hidden">
        <div class="table-container">
            <a href="{% url 'home' %}"><button type="submit" class="btn btn-primary btn-block mb-4 btn-back-to-home">
                Back to Home
            </button></a>
            <!-- Your Profile Content Goes Here -->
            <h1 class="my-5 display-5 fw-bold ls-tight text-center" style="color: hsl(218, 81%, 95%)">Profile</h1>
            
            <table class="profile-table table">
                <tr>
                    <th class="text-center">Username</th>
                    <td class="text-center">@{{ user.username }}</td>
                </tr>
                <tr>
                    <th class="text-center">First Name</th>
                    <td class="text-center">{{ user.firstname }}</td>
                </tr>
                <tr>
                    <th class="text-center">Last Name</th>
                    <td class="text-center">{{ user.lastname }}</td>
                </tr>
                <tr>
                    <th class="text-center">Email</th>
                    <td class="text-center">{{ user.email }}</td>
                </tr>
        </div>
    </section>

</body>
</html>

loginproj/authentication/templates/authentication/signin.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
      .btn-primary a{
        color: white;
        text-decoration: none;
      }
      .btn-secondary a{
        color: white;
        text-decoration: none;
      }
    </style>
</head>
<body>
    <!-- Section: Design Block -->
<section class="text-center">
    <!-- Background image -->
    <div class="p-5 bg-image" style="
          background-image: url('https://mdbootstrap.com/img/new/textures/full/171.jpg');
          height: 300px;
          "></div>
    <!-- Background image -->
  
    <div class="card mx-4 mx-md-5 shadow-lg" style="
    margin-top: -225px;
    background: hsla(0, 0%, 100%, 0.8);
    backdrop-filter: blur(30px);
    ">
    <div class="card-body py-5 px-md-5">
  
        <div class="row d-flex justify-content-center">
          <div class="col-lg-8">
            <h2 class="fw-bold mb-5">LOG IN NOW</h2>
            {% for message in messages %}
              {% if message.tags == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                  <strong>Success:</strong> {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% elif message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  <strong>Error:</strong> {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
              {% endif %}
            {% endfor %}
            <form method=POST>
              {% csrf_token %}
              
              {{ form|crispy }}

              <!-- Submit button -->
              <a href="{% url 'home' %}"><button type="submit" class="btn btn-primary btn-block mb-4">
                  Log in
              </button></a>

              <div>
                  <a href="{% url 'signup' %}"><button type="button" class="btn btn-primary btn-lg">Sign Up</button></a>
                  <a href="{% url 'customadmin:adminsignin' %}"><button type="button" class="btn btn-secondary btn-lg">Admin Login</button></a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Section: Design Block -->

  <script>
    // Add this script to handle the dismissal of alerts
    document.addEventListener('DOMContentLoaded', function () {
      var closeButtons = document.querySelectorAll('.alert .close');
  
      closeButtons.forEach(function (button) {
        button.addEventListener('click', function () {
          var alert = this.closest('.alert');
          alert.style.display = 'none';
        });
      });
    });
  </script>
</body>
</html>

loginproj/authentication/templates/authentication/signup.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body style="height: 100%; margin: 0; background-color: hsl(0, 0%, 96%);">
    <!-- Section: Design Block -->
<section class="">
    <!-- Jumbotron -->
    <div class="px-4 py-5 px-md-5 text-center text-lg-start" style="background-color: hsl(0, 0%, 96%)">
      <div class="container">
        <div class="row gx-lg-5 align-items-center">
          <div class="col-lg-6 mb-5 mb-lg-0 mt-3">
            <h1 class="my-5 display-3 fw-bold ls-tight">
              Sign Up <br />
              <span class="text-primary">Now!!!</span>
            </h1>
            
          </div>
  
          <div class="col-lg-6 mb-5 mb-lg-0">
            <div class="card">
              <div class="card-body py-5 px-md-5">
                {% for message in messages %}
              {% if message.tags == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                  <strong>Success:</strong> {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% elif message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  <strong>Error:</strong> {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
              {% endif %}
            {% endfor %}
        
                <form method="post" style="text-align: center;">
                    {% csrf_token %}
              
                    {{ form|crispy }}
    
                  <!-- Submit button -->
                  <button type="submit" value="submit" class="btn btn-primary btn-block mb-4">
                    Sign up
                  </button>
                </form>
            
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Jumbotron -->
  </section>
  <!-- Section: Design Block -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <script>
    // Add this script to handle the dismissal of alerts
    document.addEventListener('DOMContentLoaded', function () {
      var closeButtons = document.querySelectorAll('.alert .close');
  
      closeButtons.forEach(function (button) {
        button.addEventListener('click', function () {
          var alert = this.closest('.alert');
          alert.style.display = 'none';
        });
      });
    });
  </script>
</body>
</html>