loginproj/customadmin/urls.py
from django.urls import include, path
from . import views
app_name='customadmin'
urlpatterns = [
    path('adminsignin',views.adminsignin,name = 'adminsignin'),
    path('adminhome', views.adminhome, name='adminhome'),
    path('adminsignout',views.adminsignout,name = 'adminsignout'),
    path('manageusers',views.manageusers,name = 'manageusers'),
    path('deleteuser/<int:userid>',views.deleteuser,name = 'deleteuser'),
    path('edituser/<int:userid>',views.edituser,name = 'edituser'),
    path('createuser',views.createuser,name = 'createuser'),
]

loginproj/loginproj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authentication.urls')),
    path('customadmin/', include('customadmin.urls'))
]

loginproj/customadmin/models.py
from django.db import models

# Create your models here.

loginproj/customadmin/forms.py
from django import forms
from authentication.models import User
from django.forms import ModelForm

class Usereditform(forms.ModelForm):
    class Meta:
        model = User
        fields = "__all__"
        labels = {
            'firstname' : '',
            'lastname' : '',
            'email' : '',
            'username' : '',
            'password' : '',
        }
        widgets = {
            'firstname' : forms.TextInput(attrs={'placeholder':'First Name'}),
            'lastname' : forms.TextInput(attrs={'placeholder':'Last Name'}),
            'email' : forms.TextInput(attrs={'placeholder':'Email'}),
            'username' : forms.TextInput(attrs={'placeholder':'Username'}),
            'password': forms.PasswordInput(attrs={'placeholder':'Password'}),
        }

loginproj/customadmin/views.py
from django.shortcuts import redirect, render
from authentication.forms import Signinform,Signupform
from customadmin.forms import Usereditform
from django.contrib import messages
from django.views.decorators.cache import never_cache
from authentication.models import User
from django.db.models import Q

@never_cache
def adminsignin(request):
    username = 'hamraz'
    password = '123'

    if 'uname' in request.session and request.session['uname'] == username:
        return redirect('customadmin:adminhome')

    if request.method == 'POST':
        form = Signinform(request.POST)
        if form.is_valid():
            entered_username = form.cleaned_data['username']
            entered_password = form.cleaned_data['password']

            if username == entered_username and password == entered_password:  
                request.session['uname'] = entered_username                  
                return redirect('customadmin:adminhome')
            else:
                messages.error(request, 'Invalid username or password')
    
    form = Signinform()

    return render(request, 'customadmin/adminsignin.html', {'form': form})

@never_cache
def adminhome(request):
    username = 'hamraz'
    if request.session.get('uname') != username:
        return redirect('customadmin:adminsignin')
    return render(request, 'customadmin/adminhome.html')

def adminsignout(request):
    if 'uname' in request.session:
        request.session.flush()
    messages.success(request,'You have logged out successfully')
    return redirect('customadmin:adminsignin')

@never_cache
def manageusers(request):
    if 'uname' not in request.session:
        return redirect('customadmin:adminsignin')

    query = request.GET.get('q')
    users = User.objects.all()

    if query:
        users = users.filter(Q(username__icontains=query))

    context = {'users': users, 'query': query}

    return render(request, 'customadmin/manageusers.html', context)
    
def deleteuser(request,userid):
    user = User.objects.get(id = userid)
    user.delete()
    messages.success(request,'Deleted user Successfully')
    return redirect('customadmin:manageusers')

@never_cache
def edituser(request, userid):
    if 'uname' not in request.session:
        return redirect('customadmin:adminsignin')
    try:
        user_instance = User.objects.get(id=userid)
    except User.DoesNotExist:
        return redirect('customadmin:manageusers')
    if request.method == 'POST':
        form = Usereditform(request.POST, instance=user_instance)
        if form.is_valid():
            form.save()
            messages.success(request,'User details have been updated Successfully')
            return redirect('customadmin:manageusers') 
    else:
        form = Usereditform(instance=user_instance)

    return render(request, 'customadmin/edituser.html', {'form': form})

@never_cache
def createuser(request):
    if 'uname' not in request.session:
        return redirect('customadmin:adminsignin')
    else:
        if request.method == "POST":
            form = Signupform(request.POST)
            if form.is_valid():
                password = form.cleaned_data['password']
                confirm_password = form.cleaned_data['confirm_password']

                if confirm_password!=password:
                    messages.error(request, "Password's doesn't match")
                    return redirect('customadmin:createuser')
                else:
                    form.save()
                    messages.success(request, 'User created Successfully')
                    return redirect('customadmin:adminhome')
        else:
            form = Signupform()

        return render(request,'customadmin/createuser.html',{'form': form})


          

loginproj/customadmin/templates/customadmin/adminhome.html
{% extends 'customadmin/base.html' %}

{% block title %}Admin Home{% endblock %}

{% block additional_styles %}
{% endblock %}
{% block top %}
<div>
    Hey Hamraz, You can access admin page
</div>
<div class="mt-5">
    <a href="{% url 'customadmin:createuser' %}"><button type="submit" class="btn btn-success btn-block mb-4">
        Create User
    </button></a>
    <a href="{% url 'customadmin:manageusers' %}"><button type="submit" class="btn btn-primary btn-block mb-4">
        Manage Users
    </button></a>
    <a href="{% url 'customadmin:adminsignout' %}"><button type="submit" class="btn btn-danger btn-block mb-4">
        Logout
    </button></a>
</div>
{% endblock %}
{% block content %}
    <section class="text-center">
    </section>
{% endblock %}

{% block additional_scripts %}
{% endblock %}

loginproj/customadmin/templates/customadmin/adminsignin.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
      .btn-primary a{
        color: white;
        text-decoration: none;
      }
      .btn-secondary a{
        color: white;
        text-decoration: none;
      }
    </style>
</head>
<body>
    <!-- Section: Design Block -->
<section class="text-center">
    <!-- Background image -->
    <div class="p-5 bg-image" style="
          background-image: url('https://mdbootstrap.com/img/new/textures/full/171.jpg');
          height: 300px;
          "></div>
    <!-- Background image -->
  
    <div class="card mx-4 mx-md-5 shadow-lg" style="
    margin-top: -225px;
    background: hsla(0, 0%, 100%, 0.8);
    backdrop-filter: blur(30px);
    ">
    <div class="card-body py-5 px-md-5">
  
        <div class="row d-flex justify-content-center">
          <div class="col-lg-8">
            <h2 class="fw-bold mb-5">ADMIN LOG IN</h2>
            {% for message in messages %}
              {% if message.tags == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                  <strong>Success:</strong> {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% elif message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  <strong>Error:</strong> {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
              {% endif %}
            {% endfor %}
            <form method=POST>
              {% csrf_token %}
              
              {{ form|crispy }}

              <a href="{% url 'customadmin:adminhome' %}"><button type="submit" class="btn btn-primary btn-block mb-4">
                  Log in
              </button></a>
            </form>
            <a href="{% url 'signin' %}"><button class="btn btn-secondary btn-lg">
              Back to user login
            </button></a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Section: Design Block -->

  <script>
    // Add this script to handle the dismissal of alerts
    document.addEventListener('DOMContentLoaded', function () {
      var closeButtons = document.querySelectorAll('.alert .close');
  
      closeButtons.forEach(function (button) {
        button.addEventListener('click', function () {
          var alert = this.closest('.alert');
          alert.style.display = 'none';
        });
      });
    });
  </script>
</body>
</html>

loginproj/customadmin/templates/customadmin/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
      .btn-primary a{
        color: white;
        text-decoration: none;
      }
      .btn-secondary a{
        color: white;
        text-decoration: none;
      }
    </style>
    {% block heading %}
   
    {% endblock %}
</head>
<body>
    <!-- Section: Design Block -->
<section class="text-center">
    <!-- Background image -->
    <div class="p-5 bg-image" style="
          background-image: url('https://mdbootstrap.com/img/new/textures/full/171.jpg');
          height: 300px;
          "></div>
    <!-- Background image -->
  
    <div class="card mx-4 mx-md-5 shadow-lg" style="
    margin-top: -225px;
    background: hsla(0, 0%, 100%, 0.8);
    backdrop-filter: blur(30px);
    ">
    <div class="card-body py-5 px-md-5">
  
        <div class="row d-flex justify-content-center">
          <div class="col-lg-8">
            <h2 class="fw-bold mb-5">{% block top %}{% endblock %}</h2>
            {% for message in messages %}
              {% if message.tags == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                  <strong>Success:</strong> {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% elif message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  <strong>Error:</strong> {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
              {% endif %}
            {% endfor %}
            
        </div>
    </div>
      </div>
    </div>
  </section>
  <!-- Section: Design Block -->

  <script>
    // Add this script to handle the dismissal of alerts
    document.addEventListener('DOMContentLoaded', function () {
      var closeButtons = document.querySelectorAll('.alert .close');
  
      closeButtons.forEach(function (button) {
        button.addEventListener('click', function () {
          var alert = this.closest('.alert');
          alert.style.display = 'none';
        });
      });
    });
  </script>
  {% block additional_scripts %}
{% endblock %}
  {% block content %}

{% endblock %}
</body>
</html>

loginproj/customadmin/templates/customadmin/createuser.html
{% extends 'customadmin/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Create User{% endblock %}

{% block additional_styles %}
{% endblock %}
{% block top %}
<div>
    Create User
</div>
<div>
    <form method=POST>
        {% csrf_token %}
        
        {{ form|crispy }}

        <!-- Submit button -->
        <a href="{% url 'customadmin:adminhome' %}"><button type="submit" class="btn btn-primary btn-block mb-4">
            Create User
        </button></a>

    </form>
</div>
{% endblock %}
{% block content %}
    <section class="text-center">
    </section>
{% endblock %}

{% block additional_scripts %}
{% endblock %}

loginproj/customadmin/templates/customadmin/edituser.html
{% extends 'customadmin/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Edit User{% endblock %}

{% block additional_styles %}
{% endblock %}
{% block top %}
<div>
    Edit User
</div>
<div>
    <form method=POST>
        {% csrf_token %}
        
        {{ form|crispy }}

        <!-- Submit button -->
        <a href="{% url 'customadmin:adminhome' %}"><button type="submit" class="btn btn-primary btn-block mb-4">
            Update
        </button></a>

    </form>
</div>
{% endblock %}
{% block content %}
    <section class="text-center">
    </section>
{% endblock %}

{% block additional_scripts %}
{% endblock %}

loginproj/customadmin/templates/customadmin/manageusers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manage Users</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body style="margin: 0; padding: 0; height: 100%;">

    <style>
        html, body {
            margin: 0;
            padding: 0;
        }

        .background-radial-gradient {
            background-color: hsl(218, 41%, 15%);
            background-image: radial-gradient(650px circle at 0% 0%, hsl(218, 41%, 35%) 15%, hsl(218, 41%, 30%) 35%, hsl(218, 41%, 20%) 75%, hsl(218, 41%, 19%) 80%, transparent 100%), radial-gradient(1250px circle at 100% 100%, hsl(218, 41%, 45%) 15%, hsl(218, 41%, 30%) 35%, hsl(218, 41%, 20%) 75%, hsl(218, 41%, 19%) 80%, transparent 100%);
            background-size: 100% 100%;
            height: 100%;
        }

        .table-container {
            width: 80%;
            margin: 50px auto 0;
        }

        .manage-users-table {
            width: 100%;
            margin-top: 20px;
        }

        .manage-users-table th, .manage-users-table td {
            padding: 10px;
            text-align: left;
            background-color: white;
            color: hsl(218, 81%, 25%); /* Darker text for better contrast */
        }

        .btn-back-to-home {
            margin-top: 50px; /* Adjust the margin-top value as needed */
            margin-left: 70px;
        }

        h1 {
            color: #333;
        }

        .search-form {
            max-width: 400px;
            margin: 20px auto;
            background-color: #fff;
            padding: 10px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            display: flex;
            align-items: center;
        }

        label {
            display: none; /* Hide the label on small screens */
            margin-bottom: 10px;
            color: #555;
        }

        input {
            flex: 1;
            padding: 10px;
            margin-bottom: 5px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .search-btn {
            background-color: #4caf50;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            margin-left: 20px;
            margin-top: -5px;
        }

        .search-btn:hover {
            background-color: #45a049;
        }
        
    </style>

    <section class="background-radial-gradient overflow-hidden">
        <a href="{% url 'customadmin:adminhome' %}">
            <button type="submit" class="btn btn-primary btn-block mb-4 btn-back-to-home">
                Back to Home
            </button>
        </a>
        <div class="table-container table-con">
            <h1 class="my-5 display-5 fw-bold ls-tight text-center" style="color: hsl(218, 81%, 95%)">Manage Users</h1>

            <form method="GET" action="{% url 'customadmin:manageusers' %}" class="search-form">
                {% csrf_token %}
                <input type="text" name="q" value="{% if query %}{{ query }}{% endif %}" placeholder="Search User" class="form-control">
                <button type="submit" class="search-btn">Search</button>
            </form>

            <table class="manage-users-table table">
                <thead>
                    {% for message in messages %}
              {% if message.tags == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                  <strong>Success:</strong> {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% elif message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  <strong>Error:</strong> {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
              {% endif %}
            {% endfor %}
                    <tr>
                        <th class="text-center">First Name</th>
                        <th class="text-center">Last Name</th>
                        <th class="text-center">Username</th>
                        <th class="text-center">Email</th>
                        <th class="text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% if users %}
                        {% for user in users %}
                            <tr>
                                <td class="text-center text-bold">{{ user.firstname }}</td>
                                <td class="text-center">{{ user.lastname }}</td>
                                <td class="text-center">{{ user.username }}</td>
                                <td class="text-center">{{ user.email }}</td>
                                <td class="text-center">
                                    <a href="{% url 'customadmin:edituser' user.id %}" class="btn btn-warning btn-sm">Edit</a>
                                
                                    <a href="{% url 'customadmin:deleteuser' user.id %}"><button class="btn btn-danger btn-sm" >Delete</button></a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="5" class="text-center">No users found</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </section>

    <script>
        // Add this script to handle the dismissal of alerts
        document.addEventListener('DOMContentLoaded', function () {
          var closeButtons = document.querySelectorAll('.alert .close');
      
          closeButtons.forEach(function (button) {
            button.addEventListener('click', function () {
              var alert = this.closest('.alert');
              alert.style.display = 'none';
            });
          });
        });
      </script>

</body>
</html>